import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from 'react';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }: PropsWithChildren) {
return (
  <html lang="en">
    <body className="bg-gray-50 text-gray-900 min-h-screen">
      <div className="flex flex-col min-h-screen">
        <Navbar />
          <main className="flex-1 container mx-auto px-4 py-8">{children}</main>
        <Footer />
      </div>
    </body>
  </html>
  );
}